### ISSUE TITLE
Connect-Unity : Type [UnitySession] introuvable.

### ISSUE THREAD

**Issue by Tagada33** [equelin/Unity-Powershell#13]
Please makes sure these boxes are checked before submitting your issue (put an X between the brackets).

- [x ] Check that your Powershell version > 5.0 (Bonus point if you are using the latest version available)
- [x ] Check that you follow the instructions for installing the module

Also, please provide:

- Any instructions that may help to reproduce the problem
- Informations about your host `$PSVerionTable`
- The list of the loaded modules `Get-Module`

J'ai installé unity-powershell une fois celui-ci à très bien fonctionné.
J'ai voulu réutilisé le module message :

PS C:\WINDOWS\system32> Connect-Unity
Connect-Unity : Type [UnitySession] introuvable.
Au caractère Ligne:1 : 1
+ Connect-Unity
+ ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (UnitySession:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

PS C:\WINDOWS\system32> get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.1        PSReadline                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSReadlineKeyHandler, Set-PSReadlineKeyHandler...}
Script     0.11.1     Unity-Powershell                    {Connect-Unity, Disable-UnityFastCache, Disconnect-Unity, Enable-UnityFastCache...}

Suppression du module unity-powershell, réinstallation toujours même problème.

**Comment by equelin** [comment]
Bonjour et merci pour votre retour.

Pourriez-vous me fournir la version de Powershell que vous utilisez ?

```Powershell
PS > $PSVersionTable
```

**Comment by Tagada33** [comment]
Bonjour,

Voici, la version de PowerShell utilisé,

Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10240  17146

J’ai testé le module sur un autre poste, le module fonctionne. Celui-ci a une version de PS différente.
Je suis en train de faire une mise à jour de Windows 10, je vous tiens au courant de la suite.

Cordialement,


Didier BIZEAU
Consultant Stockage/SAN

[cid:image002.png@01D12611.CE7552F0]<http://www.axians.com/>

Axians Cloud Builder
6 Allée Pierre Gilles de Gennes, 33700 Mérignac
Mobile: +336 98 30 65 41
didier.bizeau@axians.com<mailto:didier.bizeau@axians.com>
axians.com<http://axians.com/>

Follow us  [twitter_icon] <https://twitter.com/AxiansCloud>  [FB_icon] <https://www.facebook.com/axians.official>  [Linkedin_icon] <https://www.linkedin.com/company/axianscloudbuilder>

  [cid:image003.jpg@01D12611.CE7552F0] <http://www.vinci-energies.com/>

APX Cloud Builder devient Axians Cloud Builder, marque du groupe Vinci Energies.<http://www.apx.fr/index.php?id=55&tx_ttnews%5Btt_news%5D=52&cHash=24adc1e0b265d8db49b2992276b3427d>

PLEASE CONSIDER OUR ENVIRONMENT BEFORE PRINTING THIS E-MAIL.

Ce message et toutes les pièces jointes sont confidentiels et établis à l'intention exclusive de ses destinataires. Toute utilisation ou diffusion non autorisée est interdite. Tout message électronique est susceptible d'altération. Axians décline toute responsabilité au titre de ce message s'il a été altéré, déformé ou falsifié. This message and any attachments are confidential and intended solely for the addressees. Any unauthorised use or dissemination is prohibited. E-mails are susceptible to alteration. Axians could not be liable for the message if altered, changed or falsified.

De : Erwan Quélin [mailto:notifications@github.com]
Envoyé : vendredi 16 décembre 2016 16:21
À : equelin/Unity-Powershell <Unity-Powershell@noreply.github.com>
Cc : BIZEAU Didier <didier.bizeau@axians.com>; Author <author@noreply.github.com>
Objet : Re: [equelin/Unity-Powershell] Connect-Unity : Type [UnitySession] introuvable. (#13)


Bonjour et merci pour votre retour.

Pourriez-vous me fournir la version de Powershell que vous utilisez ?

PS > $PSVersionTable

**Comment by Tagada33** [comment]
Bonjour,

J’ai mis à jour Powershell, le problème est résolu.

PS C:\WINDOWS\system32>  $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  0

Merci

Cordialement,


Didier BIZEAU
Consultant Stockage/SAN

[cid:image002.png@01D12611.CE7552F0]<http://www.axians.com/>

Axians Cloud Builder
6 Allée Pierre Gilles de Gennes, 33700 Mérignac
Mobile: +336 98 30 65 41
didier.bizeau@axians.com<mailto:didier.bizeau@axians.com>
axians.com<http://axians.com/>

Follow us  [twitter_icon] <https://twitter.com/AxiansCloud>  [FB_icon] <https://www.facebook.com/axians.official>  [Linkedin_icon] <https://www.linkedin.com/company/axianscloudbuilder>

  [cid:image003.jpg@01D12611.CE7552F0] <http://www.vinci-energies.com/>

APX Cloud Builder devient Axians Cloud Builder, marque du groupe Vinci Energies.<http://www.apx.fr/index.php?id=55&tx_ttnews%5Btt_news%5D=52&cHash=24adc1e0b265d8db49b2992276b3427d>

PLEASE CONSIDER OUR ENVIRONMENT BEFORE PRINTING THIS E-MAIL.

Ce message et toutes les pièces jointes sont confidentiels et établis à l'intention exclusive de ses destinataires. Toute utilisation ou diffusion non autorisée est interdite. Tout message électronique est susceptible d'altération. Axians décline toute responsabilité au titre de ce message s'il a été altéré, déformé ou falsifié. This message and any attachments are confidential and intended solely for the addressees. Any unauthorised use or dissemination is prohibited. E-mails are susceptible to alteration. Axians could not be liable for the message if altered, changed or falsified.

De : Erwan Quélin [mailto:notifications@github.com]
Envoyé : vendredi 16 décembre 2016 16:21
À : equelin/Unity-Powershell <Unity-Powershell@noreply.github.com>
Cc : BIZEAU Didier <didier.bizeau@axians.com>; Author <author@noreply.github.com>
Objet : Re: [equelin/Unity-Powershell] Connect-Unity : Type [UnitySession] introuvable. (#13)


Bonjour et merci pour votre retour.

Pourriez-vous me fournir la version de Powershell que vous utilisez ?

PS > $PSVersionTable

**Comment by equelin** [comment]
Bonjour,

Merci pour l'info. N'hésitez pas à me faire un retour (positif ou négatif !) sur le module.
Si jamais vous appréciez le module, merci de lui attribuer une "étoile" ;-)

Cordialement,
