### ISSUE TITLE
New-UnityLun, New-UnityVMwareLun do not enable compression by default, contrary to what Help tells us

### ISSUE THREAD

**Issue by mtboren** [equelin/Unity-Powershell#18]
`New-UnityLun`, `New-UnityVMwareLun` cmdlets do not enable compression on resulting Lun objects by default, though the expectation is that the cmdlets will (help says that they do).

Issue seems to be related to there being no default value actually provided in the function definitions for parameter `isCompressionEnabled`, and that the subsequent code that deals with said parameter only uses the parameter if user specified it in the call to the cmdlet.  These tidbits of code are in `New-UnityLUN.ps1` and `New-UnityVMwareLUN.ps1`, respectively.

Possible resolution is to:
- set a default value for that parameter in each of those cmdlet definitions
- check the parameter value and populate `$lunParameters["isCompressionEnabled"]` everytime in each .ps1 definition file (instead of only checking if parameter was specified, and so, only populating that `$lunParameters["isCompressionEnabled"]` value if so)

GitHub Issue Template items:

Please makes sure these boxes are checked before submitting your issue (put an X between the brackets).

- [ X ] Check that your Powershell version > 5.0 (Bonus point if you are using the latest version available)
- [ X ] Check that you follow the instructions for installing the module
  - followed "manual setup" steps

Also, please provide:

- Any instructions that may help to reproduce the problem
  - for Unity with software/firmare at a level that provides API v5, just invoking these cmdlets themselves will produce the problem (test Unity target is at software version `4.1.0`)
- Information about your host `$PSVerionTable`
``` PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
- The list of the loaded modules `Get-Module`:
``` PowerShell
ModuleType Version    Name
---------- -------    ----
Manifest   3.1.0.0    Microsoft.PowerShell.Management
Manifest   3.0.0.0    Microsoft.PowerShell.Security
Manifest   3.1.0.0    Microsoft.PowerShell.Utility
Manifest   3.0.0.0    Microsoft.WSMan.Management
Script     1.1.0.1    PSReadline
Script     0.12.0     Unity-Powershell
```

- And, some information about the storage array on which these actions were all taken (info from the REST API at URI `/api/types/basicSystemInfo/instances`):
``` PowerShell
apiVersion         : 5.0
softwareVersion    : 4.1.0
earliestApiVersion : 4.0
model              : Unity 600F
```

**Comment by equelin** [comment]
Hello @mtboren 

Good catch! This problem is a little bit similar to issue #17 because the parameter `isCompressionEnabled` has to be enabled by default only on Unity Full Flash.

You gave me a lot to think about !

**Comment by equelin** [comment]
Correction... This parameter has to be set to $True by default only if you try to create a storage resource on "Extreme Performance only" pool.

**Comment by equelin** [comment]
I've updated the develop branch with PR #25 . Compression should be enabled by default on supported arrays.
PLease test by yourself as I don't have an Unity 600F at home ;-)

**Comment by mtboren** [comment]
Greets-

Tested and confirmed: `New-UnityLUN` and `New-UnityVMwareLUN` now create LUNs on which `IsCompressionEnabled` property is `True` -- hurray!  Thanks, and I like the way in which you solved this -- surgically.

And, I assume that EMC is sending you a 600F so that you can test from home, right? `<wink/>`

**Comment by equelin** [comment]
Thanks for the feedbach @mtboren ! 

I assume that the module v0.13.0 is working well on your 600F and that I can close the others issues you opened.

**Comment by mtboren** [comment]
Yes, this issue is ready for closure (obviously -- you closed it!).

As for v0.13.0 overall, there is one new item that I have noticed, and for which I will open another Issue -- seems to be pretty minor (a missing/extraneous member in an object definition as reported at `Connect-Unity` time).

Cheers

**Comment by equelin** [comment]
Thanks for the feedback, Feel free to open an issue whenever you want.
