### ISSUE TITLE
Alert

### ISSUE THREAD

**Issue by Johngodridge** [equelin/Unity-Powershell#2]
What I really need to use the Alert call, we don't use SNMP, so I would need a CMDlet which asked for all the Alert at a certain severity level.

would this be possible to do?

once again thanks

**Comment by Johngodridge** [comment]
I have sorted this through get-unityitem

**Comment by equelin** [comment]
Hello @Johngodridge, thanks for your feedback.

This cmdlet is not implementad yet, I'll try to add it soon. 
Good to know you have been able to find a solution with Get-UnityItem!

**Comment by equelin** [comment]
The command `Get-UnityAlert` is available in the version 0.7.0

Feel free to give me any feedback.
