### ISSUE TITLE
Set -Append to True by default on Get-UnityLUN, Get-UnityVMwareLUN and Get-UnityVMwareNFS

### ISSUE THREAD

**Issue by equelin** [equelin/Unity-Powershell#28]
This issue has been created to gather ideas about the `Append` parameters in following functions:

- Set-UnityLUN
- Set-UnityVMwareLUN
- Set-UnityVMwareNFS

When modifying host access, parameter `Append` will add the new hosts to the existing configuration instead of overwriting the existing one. If you don't specify this parameter, a warning appear for explaining what will happen.

It might be safer to change this behavior to prevent some mistakes.

Some ideas:

@wright12 & @mtboren
> As for handling of host access with Set-UnityLUN, I feel, like @wright12, that making -Append default to $true is a possible solution.

@mtboren
> Another way that comes to mind is to remove the "overwrite" capability altogether by providing, for host access add/removal for a LUN, parameters -AddHost and -RemoveHost, so that it is explicit when the user is setting host access for a LUN: they are either adding or removing (or possibly both in the same call), but there is little [no?] question as to the action that they about to take. Thoughts on that?

**Comment by hillkc4** [comment]
For the case of the VMFS  and VMNFS objects it would be possible to check whether there were any vdisks stored on the objects that were about to have their access revoked. The array polls for this info and keeps a copy. It could also be retrieved from the VMware side as well. 
Working from the array side data would take some care. The array polls for this info with low frequency so you would likely want to force a refresh to make sure the info was as current as possible.
