### ISSUE TITLE
Get_UnityLun

### ISSUE THREAD

**Issue by Johngodridge** [equelin/Unity-Powershell#3]
I have been testing the Get-UnityLun function and no matter the amount of data add SizeUsed is still 0

PS C:\Users\Administrator.GIO-STOR-MAN1> Get-UnityLun

Name    id   pool   isThinEnabled tieringPolicy sizeTotal    sizeUsed sizeAllocated

---

testlun sv_1 pool_1 True          Autotier_High 107374182400 0        203866112  
test2   sv_2 pool_1 True          Autotier_High 64424509440  0        0

**Comment by Johngodridge** [comment]
so its seems it not need and I sort of agree, you would get this info from the host
izeUsed

unsigned Integer[64(bytes)]

Used size is not applicable to LUN and this value is not set.

**Comment by equelin** [comment]
Yes you're right. I don't know why they implemented this parameter if it's not used...
 I'll correct that in a later release.

**Comment by equelin** [comment]
This issue as been corrected in the release v0.6.2.
