### ISSUE TITLE
Get-UnitySystem throw an error with physical Unity arrays

### ISSUE THREAD

**Issue by barnette08** [equelin/Unity-Powershell#33]
Please makes sure these boxes are checked before submitting your issue (put an X between the brackets).

- [X] Check that your Powershell version > 5.0 (Bonus point if you are using the latest version available)
**Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  117**

- [X] Check that you follow the instructions for installing the module
**Manual Installation**

Also, please provide:

- Any instructions that may help to reproduce the problem
**I get similar errors about .NET objects when connecting to the array.  What version of code was this testing with on the Unity side?**

**New-Object : The member "avgPower" was not found for the specified .NET object.**

- Informations about your host `$PSVerionTable`
**Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  117**

- The list of the loaded modules `Get-Module`
**ModuleType Version    Name
---------- -------    ----
Manifest   3.1.0.0    Microsoft.PowerShell.Management
Manifest   3.0.0.0    Microsoft.PowerShell.Security
Manifest   3.1.0.0    Microsoft.PowerShell.Utility
Binary     1.0.0.1    PackageManagement
Script     1.0.0.1    PowerShellGet
Script     0.14.0     Unity-Powershell**

**Comment by equelin** [comment]
Hello @barnette08,

Thanks for your feedback !

My understanding is that you've got those kind of error messages for every commands, is that right ? If not could you provide the names of the commands ?

The module has been tested with physical and virtual arrays but I don't have possibility to every different model with every software versions. What's your Unity array ?

**Comment by barnette08** [comment]
I'm getting the errors for most commands but some work.  I think I've figured out that it may be a Unity code version incompatibility.  I have tested pool, lun, and drive commands in versions 4.1.0, 4.1.2, and even newer future versions.  Am I correct in assuming you developed this against 4.0.0?  The latest release from Dell EMC is 4.1.2.9257522. 

Even when connecting (regardless of code revision on the array 4.0.2, 4.1.0, 4.1.2, future) I get the below error:

New-Object : The member "avgPower" was not found for the specified .NET object.

**Comment by equelin** [comment]
Hello,
This module has been developped first with the 4.0.0 version and has been updated when EMC released 4.1.X code.
Would you mind to provide a more detailed output of the error messages and an example ? You may run those commands with the `-debug` and `-verbose` parameters.
For information, the property `avgPower` is related to commands like `Get-UnityDae` and `Get-UnityDpe`, I'm not sure to understand why you've got this message for other commands.

**Comment by barnette08** [comment]
When running Connect-Unity -debug -verbose, below is a section of the failure output:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: [ConvertTo-Hashtable] Executing function

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
New-Object : The member "avgPower" was not found for the specified .NET object.
At line:64 char:21
+                     New-Object -TypeName $TypeName -Property $Result
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.NewObjectCommand

DEBUG: [Get-UnityBasicSystemInfo] Executing function

**Comment by equelin** [comment]
Ok thanks, do you confirm that even with this error message you can connect to the Unity and use others commands ?

Could you provide the exact model of the Unity ?

**Comment by barnette08** [comment]
Just to answer your other question, I ran through the other Get commands and the following give errors for me as well.


Get-UnityEthernetPort
New-Object : The value supplied is not valid, or the property is read-only. Change the value, and then try again
At line:64 char:21

Get-UnitySystem
New-Object : The member "avgPower" was not found for the specified .NET object.
At line:64 char:21

I get more errors in the beta release but that makes sense of course since this wasn't developed against it.

**Comment by barnette08** [comment]
The model running 4.1.2 is a Unity 500 and another one I tested running 4.1.0 is a Unity 300.  Both get the same errors as above.

**Comment by equelin** [comment]
I may have an idea.

Is it possible to connect to an Unity and run this command and provide the output ?

```Powershell
((Get-UnityItem -URI /api/types).Entries.content | Where-Object {$_.name -eq 'system'}).attributes
```

**Comment by barnette08** [comment]
I didn't provide the description, but here is the rest of the output:

name                  type
----                  ----
id                    String
health                health
name                  String
model                 String
serialNumber          String
internalModel         String
platform              String
macAddress            String
isEULAAccepted        Boolean
isUpgradeComplete     Boolean
isAutoFailbackEnabled Boolean
currentPower          Integer
avgPower              Integer

**Comment by equelin** [comment]
OK I see, thanks for the feedback. So the online documentation is not up to date (or is different depending of the model...). I'm going to push a patch in the develop branch, do you have the possibility to test it ?

**Comment by barnette08** [comment]
Yes I can test it.  

Also, I'm not sure if this is important or not but if you don't issue the disconnect-unity command when closing powershell (and issue exit or close the window) the module doesn't response in a new window and will not allow connect-unity.  In order to get around this I had to reinstall the module.

By the way, this is outstanding work and is much appreciated!!

**Comment by equelin** [comment]
Thank you!

The fix is available in the develop branch ;-)

**Comment by barnette08** [comment]
I've tested the change and I get the below now on connect-unity in the same section as before from the verbose output, but for isAutoFailbackEnabled now.

Connect-Unity
New-Object : The member "isAutoFailbackEnabled" was not found for the specified .NET object.

Get-UnityEthernetPort
New-Object : The value supplied is not valid, or the property is read-only. Change the value, and then try again.

Get-UnitySystem
New-Object : The member "isAutoFailbackEnabled" was not found for the specified .NET object.

**Comment by equelin** [comment]
My bad... Really sorry, would you mind to do another test ?

**Comment by barnette08** [comment]
That cleared up the connect-unity and get-unitysystem issues in 4.1.x, but not in the beta (just FYI on that).  Get-unityethernetport still returns errors, not sure if you want to just track that as a different issue - since the other two are related?

**Comment by equelin** [comment]
Great !

I've opened another issue #34 for the error with Get-UnityEthernetPort.
