### ISSUE TITLE
[WIP] Release 0.15

### ISSUE THREAD

**Issue by equelin** [equelin/Unity-Powershell#37]
This issue is intended to gather all enhancement / modification added to the next release 0.15. It'll be used to create the release note.

**Comment by equelin** [comment]
# Unity-Powershell 0.15.0
## New features

- Added support for code Merlin (4.2.X) and related API
- Added functions for services the system. It's now possible to enable or disable SSH and generate/download data collections for troubleshooting purpose
    - `Get-UnityServiceInfo`
    - `Get-UnityServiceAction`
    - `Get-UnityDataCollectionResult`
    - `Set-UnityServiceAction`
- Added `Save-DataCollectionResult` function that simplify data collection generation and download. Useful for example when you want to automate Mitrend Assessments request for your Unity arrays

```Powershell
Save-UnityDataCollectionResult -dataCollectionProfile 'Default' -Path 'C:' -Compress
```
> You can find [here](https://github.com/equelin/PSMitrend/blob/master/Examples/UnityAssessment.ps1) a script that will completly automate the request of an Unity assessment with the powershell module [PSMitrend](https://github.com/equelin/PSMitrend).
- Added functions to gather informations about hardware:
    - `Get-UnityBattery`
    - `Get-UnityFCPort`
- Added function Get-UnityX509Certificate to get informations about X509 certificates
- Added functions to gather informations about VMware vVol Protocol Endpoints:
    - `Get-UnityvmwarePE`
    - `Get-UnityvmwareNasPEServer` 

## Breaking changes

- Some functions have been renamed to follow powershell naming conventions

Previous Name (<0.15) | Actual Name
-- | --
Get-UnityMgmtInterfaceSettings | Get-UnityMgmtInterfaceSetting
Set-UnityMgmtInterfaceSettings | Set-UnityMgmtInterfaceSetting



## Enhancement

- Added non terminating errors to GET functions when an object is not found. This can be useful to add smarter tests in scripts like this:

```Powershell
If (-not (Get-UnityLUN -Name 'LUN01')) {
    New-UnityLUN -Name 'LUN01' -Size 10GB - Pool 'pool_1'
}
```

## Behind the scene

- Unity objects are now instantiated with the `New-UnityObject` private function. This function is a bit faster than the previous one and fixed known issues (#34)
- Started replacing private's function by classe's methods. Mid term objective is to translate all private functions  
- Added exports of /api/types for:
    - Unity 400F with code 4.1 and 4.2
    - Unity VSA with code 4.2
- Added enhancement to the Build-Module'script (\Tools\Build-Module) that will help to automatically generate docs, ps1xml files and update module's manifest
- Added private function Get-UnityObject (and related Pester's tests) that allow to refer to an Unity object by ID or by the actual object. This simplifies code for functions asking for an object or an ID as a parameter (mostly SET and REMOVE functions)

**Comment by equelin** [comment]
Dear Unity-Powershell users/contributors, 

I think that I'll release the version 0.15 quite soon and before that I would love to have your feedback. I'll be glad if you could test the code in the `develop` branch. 

Thanks

Ping: @mtboren @BrandonStiff @hillkc4 @wright12 @barnette08 @khill26 @bottkars

**Comment by mtboren** [comment]
Afternoon, @equelin -

Hurray, updates!  I did some preliminary testing, and made the following observations.

The Good:
- I like the adds of the cmdlets, including the VMware PE ones and the ones to manage the Unity Services themselves -- nice!
- You have resolved a [non-reported] issue that we have been having in which `Connect-Unity` would throw the following error in our environment (in v0.14.2 and an earlier version):
```PowerShell
New-Object : The value supplied is not valid, or the property is read-only. Change the value, and then try again.
At line:64 char:21
+                     New-Object -TypeName $TypeName -Property $Result
...
```
Again, that is now fixed -- yay!


The couple of observations on potential improvements that I made are very minor -- just around consistency, really.  First table is for capitalization of each noun in the the cmdlet names (CurrentName and SuggestName columns), and the second table is just about the PowerShell convention of "singular nouns in the cmdlet names"

orthography (capitalization, in this case):

CurrentName | SuggestedName
--------|----------
Get-Unitybattery	| Get-UnityBattery
Get-UnitydataCollectionResult	| Get-UnityDataCollectionResult
Get-Unitydatastore	| Get-UnityDatastore
Get-UnityfastVP	| Get-UnityFastVP
Get-UnityfcPort	| Get-UnityFCPort
Get-UnityinstalledSoftwareVersion	| Get-UnityInstalledSoftwareVersion
Get-UnitylinkAggregation	| Get-UnityLinkAggregation
Get-UnityserviceAction	| Get-UnityServiceAction
Get-UnityserviceInfo | Get-UnityServiceInfo
Get-UnitystorageResource | Get-UnityStorageResource
Get-UnityvmwareNasPEServer	| Get-UnityVMwareNasPEServer
Get-UnityvmwarePE	| Get-UnityVMwarePE
Get-Unityx509Certificate	| Get-UnityX509Certificate



singular noun for cmdlets:

CurrentName | SuggestedName
--------|----------
Get-UnityMgmtInterfaceSettings	| Get-UnityMgmtInterfaceSetting
Set-UnityMgmtInterfaceSettings	| Set-UnityMgmtInterfaceSetting


----
Then, there were a couple of cmdlets that threw errors and returned semi-complete objects, seemingly.  They are:

- `Get-UnityDisk`:
error (below), `Get-UnityDisk` returns some disk objects, all with RawSize of 0 bytes (present in v0.14.2, too, apparently)
``` PowerShell
PS C:\> Get-UnityDisk

New-Object : The value supplied is not valid, or the property is read-only. Change the value, and then try again.
At line:64 char:21
+                     New-Object -TypeName $TypeName -Property $Result
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-Object], Exception
    + FullyQualifiedErrorId : SetValueException,Microsoft.PowerShell.Commands.NewObjectCommand
```
Information about the environment in which I am testing:
``` PowerShell
PS C:\> Get-UnityBasicSystemInfo | fl *

id                 : 0
model              : Unity 600F
name               : SomeUnityArray
softwareVersion    : 4.2.0
apiVersion         : 6.0
earliestApiVersion : 4.0
```


- `Get-UnityEthernetPort`:
error (below), `Get-UnityEthernetPort` returns some ethernetPort objects, some errors (present in v0.14.2, too, apparently)
``` PowerShell
PS C:\> Get-UnityEthernetPort

Id       Name                                  StorageProcessor PortNumber ConnectorType Mtu  NeedsReplacement
--       ----                                  ---------------- ---------- ------------- ---  ----------------
spa_eth2 SP A Ethernet Port 2                  @{id=spa}        2          RJ45          1500 False
spa_eth3 SP A Ethernet Port 3                  @{id=spa}        3          RJ45          1500 False
New-Object : The value supplied is not valid, or the property is read-only. Change the value, and then try again.
At line:64 char:21
+                     New-Object -TypeName $TypeName -Property $Result
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-Object], Exception
    + FullyQualifiedErrorId : SetValueException,Microsoft.PowerShell.Commands.NewObjectCommand

New-Object : The value supplied is not valid, or the property is read-only. Change the value, and then try again.
At line:64 char:21
+                     New-Object -TypeName $TypeName -Property $Result
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-Object], Exception
    + FullyQualifiedErrorId : SetValueException,Microsoft.PowerShell.Commands.NewObjectCommand

spa_mgmt SP A Management Port                  @{id=spa}        0          RJ45          1500 False
...
```

I'm not sure if those are just around difference between the virtual edition and the physical edition that you / I are using.  Let me know what other info will be helpful for troubleshooting.

**Comment by equelin** [comment]
Hey @mtboren, I love that kind of feedback, thank you!

## Powershell naming convention

You're right. I've been a bit lazy when defining those function's names... For my defense, the GET functions are now automatically generated and the name is based on the API type's names. I guess that the Unity's engineers don't follow the same conventions ;-)

The names have been corrected on the develop branch.

## Errors on `Get-UnityDisk` and `Get-UnityEthernetPort`

I believe that this issue has been corrected in the develop branch, but I currently don't have access to a physical array so I can't test it... Would you mind to do some tests by yourself ?

Regards,

**Comment by equelin** [comment]
## New features

- Added `Save-DataCollectionResult` function that simplify data collection generation and download. Useful for example when you want to automate Mitrend Assessments request for your Unity arrays

```Powershell
Save-UnityDataCollectionResult -dataCollectionProfile 'Default' -Path 'C:' -Compress
```
> You can find [here](https://github.com/equelin/PSMitrend/blob/master/Examples/UnityAssessment.ps1) a script that will completly automate the request of an Unity assessment with the powershell module [PSMitrend](https://github.com/equelin/PSMitrend)

## Breaking changes

- Some functions have been renamed to follow powershell naming conventions

Previous Name (<0.15) | Actual Name
-- | --
Get-UnityMgmtInterfaceSettings | Get-UnityMgmtInterfaceSetting
Set-UnityMgmtInterfaceSettings | Set-UnityMgmtInterfaceSetting

## Behind the scene

- Unity objects are now instantiated with the `New-UnityObject` private function. This function is a bit faster than the previous one and fixed known issues (#34)

**Comment by mtboren** [comment]
Hello, @equelin -- sure thing, glad to try to help!

Nice, looks like you handled the naming items, as you said.  Yeah, we need to get after those Unity developers -- consistency, y'all! Though, I'm somewhat sure they are not keeping "good PowerShell practices" in mind as they develop their non-PowerShell-specific API :)

As for the errors on `Get-UnityDisk` and `Get-UnityEthernetPort` cmdlets, and testing the updated code against a physical array, I made the time to do so, and here are the results (along with one other cmdlet whose name could use some capitalization attention):
### Cmdlet naming
Capitalization:  Looks like you addressed all of those reported, but I see one more that I had not reported last time (new cmdlet, I think):
current | suggested
--------|----------
Get-Unityjob	| Get-UnityJob


### Get-UnityDisk:
error (below), `Get-UnityDisk` returns disk objects, but is now unhappy with the `estimatedEOL` value received from API and that is used to try to make a property value of .NET type `DateTime`.

My observation:  it appears that the Unity API value returned for `estimatedEOL` property is a `DateTime[Interval]` per the API docs, whatever that is -- seems like a timespan-like item, but of the format of "hour:min:sec.msec", instead of a timespan format that .NET expects where the "hour" field value range is 0-23, and there would then be a "day" value in the timespan string if it is one day or longer... 

The error (I took out the "Confirm" lines from the debugging output, and chopped out a couple fo non-pertinent sections, replacing them with elipses to keep this output a bit shorter):
``` PowerShell
PS C:\> Get-UnityDisk -Debug | select -First 1
DEBUG: [Get-UnityDisk] Executing function
DEBUG: Processing Session: myunity.dom.com with SessionId: 00000000-2222-3333-4444-111111111111
DEBUG: [Get-UnityItemByKey] Executing function
DEBUG: [Get-URLFromObjectType] Executing function
DEBUG: [Get-URLFromObjectType] Object Type: UnityDisk
DEBUG: [Get-URLFromObjectType] Returning URL: https://myunity.dom.com/api/types/disk/instances?fields=isInUse,bank,vendorSize,maxSpeed,id,wwn,parentDae,parentDpe,isFastCacheInUse,bankSlotNumber,emcPartNumber,tierType,isSED,size,model,diskGroup,bankSlot,name,version,manufacturer,rawSize,pool,needsReplacement,parent,currentSpeed,slotNumber,diskTechnology,emcSerialNumber,estimatedEOL,busId,rpm,health&compact=true
DEBUG: [Get-UnityItemByKey] URL: https://myunity.dom.com/api/types/disk/instances?fields=isInUse,bank,vendorSize,maxSpeed,id,wwn,parentDae,parentDpe,isFastCacheInUse,bankSlotNumber,emcPartNumber,tierType,isSED,size,model,diskGroup,bankSlot,name,version,manufacturer,rawSize,pool,needsReplacement,parent,currentSpeed,slotNumber,diskTechnology,emcSerialNumber,estimatedEOL,busId,rpm,health&compact=true
DEBUG: [Send-UnityRequest] Executing function
DEBUG: [Find-FromFilter] Executing function
DEBUG: [Find-FromFilter] Found 50 item(s). Filtering result(s) on parameter Name with value *
DEBUG: [Find-FromFilter] Found 50 item(s)
DEBUG: [New-UnityObject] Executing function
DEBUG: [New-UnityObject] ParameterSetName: __AllParameterSets
DEBUG: [New-UnityObject] PSBoundParameters: 
Key      Value                                                                                                         
---      -----                                                                                                         
TypeName UnityDisk                                                                                                     
Data     {@{id=dae_1_0_disk_0; tierType=10; diskTechnology=7; health=; needsReplacement=False; parent=; slotNumber=0...
DEBUG: [New-UnityObject] No value to add to Key: bank
DEBUG: [New-UnityObject] No value to add to Key: bankSlot
DEBUG: [New-UnityObject] No value to add to Key: bankSlotNumber
DEBUG: [New-UnityObject] Add key: busId with value: 1
DEBUG: [New-UnityObject] Add key: currentSpeed with value: 12000000000
DEBUG: [New-UnityObject] Add key: diskGroup with value: @{id=dg_29}
...
DEBUG: [New-UnityObject] Add key: emcSerialNumber with value: 012345678901
DEBUG: [New-UnityObject] Add key: estimatedEOL with value: 43800:00:00.000
Exception setting "estimatedEOL": "Cannot convert value "43800:00:00.000" to type "System.DateTime". Error: "String was 
not recognized as a valid DateTime.""
At line:29 char:46
+                 $Object."$($_.name)" = $D."$($_.name)"
+                                              ~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
Exception setting "estimatedEOL": "Cannot convert value "43800:00:00.000" to type "System.DateTime". Error: "String
was not recognized as a valid DateTime.""
At line:29 char:46
+                 $Object."$($_.name)" = $D."$($_.name)"
+                                              ~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting

DEBUG: [New-UnityObject] Add key: health with value: @{value=5; descriptionIds=System.Object[]; descriptions=System.Object[]}
DEBUG: [New-UnityObject] Add key: id with value: dae_1_0_disk_0
...
DEBUG: [New-UnityObject] Add key: wwn with value: 06:00:00:00:05:00:ab:cd:ef:0a:00:00:00:00:00:03

>> TerminatingError(): "The pipeline has been stopped."
>> TerminatingError(): "The pipeline has been stopped."
Id             Name            Rawsize       DiskTechnology Rpm Bankslot
--             ----            -------       -------------- --- --------
dae_1_0_disk_0 DAE 1 0 Drive 0 3135326126080 SAS_FLASH_3    0

```

### Get-UnityEthernetPort
Getting a different error, now:
```PowerShell
PS C:\> Get-UnityEthernetPort

Id       Name                                  StorageProcessor PortNumber ConnectorType Mtu  NeedsReplacement
--       ----                                  ---------------- ---------- ------------- ---  ----------------
spa_eth2 SP A Ethernet Port 2                  @{id=spa}        2          RJ45          1500 False
spa_eth3 SP A Ethernet Port 3                  @{id=spa}        3          RJ45          1500 False
Exception setting "sfpSupportedProtocols": "Cannot convert value "2" to type "SFPSpeedValuesEnum" due to enumeration
values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration
values are "Auto,_10Mbps,_100Mbps,_1Gbps,_1500Mbps,_2Gbps,_3Gbps,_4Gbps,_6Gbps,_8Gbps,_10Gbps,_12Gbps,_16Gbps,_32Gbps,_
40Gbps,_100Gbps,_1Tbps"."
At line:29 char:46
+                 $Object."$($_.name)" = $D."$($_.name)"
+                                              ~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
...
```

Let me know what other info I can provide, or what else to test. Cheers!

**Comment by equelin** [comment]
Hello @mtboren, thanks again for your precious feedbacks! I really appreciate...

### Cmdlet naming

Done! I need to have a chat with Michael Dell and Jeffrey Snover to see if this guys can make a deal about Powershell naming's convention...

### Get-UnityEthernetPort

My bad, wrong parameter type... I need to avoid this kind of issues with Pester's tests!

### Get-UnityDisk

You're right about that bug... The `estimatedEO` parameter's type is now `[object]`... I'll try to fix this in a later release.

**Comment by equelin** [comment]
Hello @mtboren,
Sorry to bother you but did you find time to look at those issues? I'd love to have your feedback before publishing the 0.15 version.
Regards,

**Comment by mtboren** [comment]
Hey, @equelin -

Ah, yes -- when I saw your commanding comment that you had fixed some things and slated another item for a future release, I trusted that all was good -- I did not initiate another round of testing at the time.

I have done such testing now, though, and confirm that, as you said, the cmdlet naming is all better and `Get-UnityEthernetPort` now works like a champ!  I'll watch for the fix for `Get-UnityDisk`, or share a suggestion if I come up with one.

And, no bother, I'm glad to try to help.  Thank you for making this great module for the world!

Cheers, Matt

**Comment by equelin** [comment]
Hello @mtboren, my bad, my message was not really clear...

I'm shipping v0.15.0 today, I'll see in later release if I can find something clever about that `Get-UnityDisk` issue.

Thanks again for your help!

**Comment by equelin** [comment]
:shipit:

**Comment by mtboren** [comment]
Greets, @equelin -

No problemo.  And congrats on shipping -- woo-hoo! 👍 👍 

Matt
