### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by erosal** [equelin/Unity-Powershell#4]
I am receiving the following when trying to connect to Unity.  Not sure what UnitySession is referring to.
C:\WINDOWS\system32 Connect-Unity -server 1.2.3.4
Connect-Unity : Unable to find type [UnitySession].
At line:1 char:1
- Connect-Unity -server 10.98.30.51
- ~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (UnitySession:TypeName) [], RuntimeException
  - FullyQualifiedErrorId : TypeNotFound

**Comment by equelin** [comment]
Hello,

Thanks for testing Unity-Powershell. Would you mind to tell me how do you install the module and what version of powershell you are using ?

You can find the powershell version with this command:

``` Powershell
> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  122
```

Please note that you need at least Powershell 5 to be able to use this module.

**Comment by erosal** [comment]
Thanks for your quick reply and I am looking orward to test the module.
I follow your instructions to install the module

> Install-Module Unity-Powershell -Repository PSGallery

You are installing the module(s) from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet.
Are you sure you want to install software from 'https://www.powershellgallery.com/api/v2/'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a

> Import-Module Unity-Powershell -force

And I am running version 5

Major  Minor  Build  Revision

---

5      0      10240  16384

Thanks again.
Erwin

**Comment by equelin** [comment]
OK, it sounds good.

Could you provide me the output of the command `get-module Unity-Powershell` ?

**Comment by erosal** [comment]
Here you go.

ModuleType Version    Name                                ExportedCommands

---

Script     0.7.0      Unity-Powershell                    {Connect-Unity, Disable-UnityFastCache, Disconnect-Unity, Enable-UnityFastCache...}

**Comment by equelin** [comment]
By any chances, do you have the opportunity to tests with another computer (with a higher version of Powershell) or could you update your own computer ?

Thanks

**Comment by erosal** [comment]
Tried it on a powershell 5.0.10514.6 and it works like a champ.
Thanks,
Erwin

**Comment by equelin** [comment]
Good to hear that !

By the way don't hesitate to give me some feedback ;-)
