### ISSUE TITLE
How to Perform a thin clone?

### ISSUE THREAD

**Issue by stupidcomputers** [equelin/Unity-Powershell#47]
Please makes sure these boxes are checked before submitting your issue (put an X between the brackets).

- [ X] Check that your Powershell version > 5.0 (Bonus point if you are using the latest version available)
- [ X] Check that you follow the instructions for installing the module

Also, please provide:

- Any instructions that may help to reproduce the problem
- Informations about your host `$PSVerionTable`
- The list of the loaded modules `Get-Module`

I need some help with the steps to automate production of a thin clone.  It is not clear to me by using the powershell commandlets available how to create and update thin clones.  The unity web UI makes this easy.  How can I accomplish it via powershell?

Thanks,

Steve

**Comment by equelin** [comment]
Here we go !

https://github.com/equelin/Unity-Powershell/releases/tag/0.16.0

This is now possible in the 0.16.0 version of the module.

**Comment by stupidcomputers** [comment]
Rock on!  Gave this a try today and I was able to successfully invoke a thin client refresh via powershell.

Thanks!  This is a life saver.

Steve

**Comment by equelin** [comment]
I'm glad I could help ;-)

**Comment by equelin** [comment]
@stupidcomputers , if you mind to share your code, that would be awesome ;-)

Regards,

**Comment by stupidcomputers** [comment]
I would be happy to share my code.  Let me clean it up and I will send you a copy.

Steve

**Comment by stupidcomputers** [comment]
Hi Erwan,

I have a question regarding setting the –host parameter with the set-unityvmwarelun command.  I receive a 500 server error when I force a LUN refresh to a thin clone that has already been mounted (access) by my esxi hosts.  If remove host access, the refresh completes successfully.

The array sends an error message:

“Error code: InternalServerError
Error description: Internal Server Error
Error details: {"error":{"errorCode":108008715,"httpStatusCode":500,"messages":[{"en-US":"The system encountered an unexpected error. Search for the error code on the
support website or product forums, or contact your service provider, if available. (Error Code:0x670150b)"}],"created":"2017-12-07T00:37:57.142Z"}}

Invoke-WebRequest : The remote server returned an error: (500) Internal Server Error.
At line:33 char:15
+ ...     $data = Invoke-WebRequest -Uri $URI -ContentType "application/jso ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
“
My next thought was to remove host access to the LUN before I initiate a thin clone refresh and then grant host access again once the refresh is complete.  I attempted to throw the existing hostaccess data into a variable and apply it back, but it errors looking for additional array data.  Do you know what kind of data I need to provide in order to successfully complete the command?

Error:
“
PS C:\Windows\system32> Set-UnityVMwareLUN -name $clonevol -host
Set-UnityVMwareLUN : Missing an argument for parameter 'host'. Specify a parameter of type 'System.String[]' and try again.
At line:1 char:36
+ Set-UnityVMwareLUN -name $clonevol -host
+                                    ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-UnityVMwareLUN], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,Set-UnityVMwareLUN
$hosts = Get-UnityHost

PS C:\Windows\system32> Set-UnityVMwareLUN -name $clonevol -host $hosts
cmdlet Set-UnityVMwareLUN at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
ID[0]: !?
LUN ID or LUN Object
ID[0]: 1
ID[1]: 2
ID[2]: 3
ID[3]: 4
ID[4]: 5
ID[5]: 6
ID[6]: 7
ID[7]: 8
ID[8]:

“

Thanks for any help!  Attached is some of the powershell code I am working on.  I would be happy to share the complete set of scripts to allow a scheduled windows task to fully unmount and remount refreshed disks if you want.

Steve

Steve Schultz
Systems & Network Administrator
Verathon, Inc.
425-867-1348 x5619 Office
425-951-0315 Cell
Email: steve.schultz@verathon.com<mailto:steve.schultz@verathon.com>
