### ISSUE TITLE
Set-UnityNFSShare not working

### ISSUE THREAD

**Issue by jcgpro** [equelin/Unity-Powershell#48]
Please makes sure these boxes are checked before submitting your issue (put an X between the brackets).

- [ x ] Check that your Powershell version > 5.0 (Bonus point if you are using the latest version available)
- [x ] Check that you follow the instructions for installing the module

PS C:\Users\jgov> Set-UnityNFSShare -id 'NFSShare_18' -rootAccessHosts Host_4 -append
VERBOSE: GET https://172.23.18.90/api/types/system/instances with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; version=1.0;charset=UTF-8
VERBOSE: [Get-UnityObject] Object Type is String
VERBOSE: GET https://172.23.18.90/api/types/system/instances with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; version=1.0;charset=UTF-8
VERBOSE: GET
https://172.23.18.90/api/types/nfsShare/instances?fields=id,type,role,filesystem,snap,name,path,exportPaths,description,isReadOnly,creationTime,modificationTime,defaultAccess,minSecurity,noAccessHosts,readOnlyHosts,readWriteHosts,rootAccessHosts&compact=true with 0-byte
 payload
VERBOSE: received -1-byte response of content type application/json; version=1.0;charset=UTF-8
VERBOSE: [Get-UnityObject] Object ID: NFSShare_18,Object Name: NFSSHARE01
VERBOSE: GET https://172.23.18.90/api/types/system/instances with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; version=1.0;charset=UTF-8
VERBOSE: GET
https://172.23.18.90/api/types/storageResource/instances?fields=description,health,name,id,type,isReplicationDestination,replicationType,sizeTotal,sizeUsed,sizeAllocated,thinStatus,compressionStatus,compressionSizeSaved,compressionPercent,compressionRatio,esxFilesystemM
ajorVersion,esxFilesystemBlockSize,snapSchedule,isSnapSchedulePaused,relocationPolicy,perTierSizeUsed,blockHostAccess,metadataSize,metadataSizeAllocated,snapsSizeTotal,snapsSizeAllocated,snapCount,vmwareUUID,pools,datastores,filesystem,hostVVolDatastore,luns,moves,virtu
alVolumes&compact=true with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; version=1.0;charset=UTF-8
VERBOSE: {
    "nfsShareModify":  {
                           "nfsShareParameters":  {
                                                      "rootAccessHosts":  [
                                                                              {
                                                                                  "id":  "Host_4"
                                                                              },
                                                                              {
                                                                                  "id":  "Subnet_2"
                                                                              }
                                                                          ],
                                                      "isReadOnly":  false
                                                  },
                           "nfsShare":  {
                                            "id":  "NFSShare_18"
                                        }
                       }
}
VERBOSE: URL: https://172.23.18.90/api/instances/storageResource/res_31/action/modifyFilesystem

Confirm
Are you sure you want to perform this action?
Performing the operation "Modify NFS Share NFSSHARE01" on target "VIRT1641V2PBN1".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y
VERBOSE: POST https://172.23.18.90/api/instances/storageResource/res_31/action/modifyFilesystem with -1-byte payload
The array sends an error message:

Error code: 422
Error description: Unprocessable Entity
Error details: {"error":{"errorCode":131149877,"httpStatusCode":422,"messages":[{"en-US":"Request body is not correct. There may be duplicate parameters, wrong parameter name. Please refer to API documentation page and ensure the body is correct. (Error Code:0x7d13035)"}
],"created":"2018-01-16T16:21:26.457Z"}}

Invoke-WebRequest : The remote server returned an error: (422) Unprocessable Entity.
At line:33 char:15
+ ...     $data = Invoke-WebRequest -Uri $URI -ContentType "application/jso ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by equelin** [comment]
Thanks for the feedback @jcgpro 

This issue will be tracked in issue #53
