### ISSUE TITLE
Cannot connect to Unity Storage Array

### ISSUE THREAD

**Issue by agnosticcloud** [equelin/Unity-Powershell#49]
Hi,
I am trying to connect to Unity using the **connect-Unity** command, but it returns "Warning: You are no longer connected to EMC Unity array:<IP address>".
I have installed the module using the command Install-Module and imported the module using Import-Module, but I still get the same message. 
I have read few online documents and they suggest to create own objects with .Net framework for Unity-Powershell, not sure what this meant exactly. Doesn't connect-Unity command call the API behind the scenes?
Also if I have to create the .Net objects, where do I create them and how do I use them to connect to Unity? ( I am new to scripting, so not much familiar with API's)
We are stuck at the first step with no clue of what's happening, any help would be appreciated.
Thank you in advance.

- [X] Check that your Powershell version > 5.0 (Bonus point if you are using the latest version available)
- [X] Check that you follow the instructions for installing the module

Also, please provide:

- Any instructions that may help to reproduce the problem
- Informations about your host `$PSVerionTable`
- The list of the loaded modules `Get-Module`

**Comment by equelin** [comment]
Hello @arjun987,

Thanks for your interest in Unity-Powershell.

Would you mind to include more informations like the exact command your are using to connect to the array and the output of the error.
It could be hepfull if you add the output of the `$PSVersionTable` variable and the `Get-Module` command.

Regards

**Comment by agnosticcloud** [comment]
Hi equelin,

Thanks for your response.
I was using connect-unity command and the PowerShell version is 5.0. That being said, I upgraded PowerShell to 5.1 and it is working now.
But I do have a couple of questions, appreciate if you can help with them.
1. Is it mandatory to run the Install-Module Unity-PowerShell command every time, before we perform any operation?
2. Is the Unity-PowerShell officially supported by EMC Unity?

Regards

**Comment by equelin** [comment]
1. Is it mandatory to run the Install-Module Unity-PowerShell command every time, before we perform any operation?

_No you just need to import the module every time you start a new PowerShell session._

2. Is the Unity-PowerShell officially supported by EMC Unity?

_Not at all. It's an open source project bcked by the community (mostly me in fact ;-) )._

**Comment by agnosticcloud** [comment]
Thank you equelin
