### ISSUE TITLE
Add LUNs to consistency Group

### ISSUE THREAD

**Issue by agnosticcloud** [equelin/Unity-Powershell#51]
Hi,

This is not an issue, but I am looking for a command to add Newly created/Existing LUNs to Consistency group. I checked all the command in the documentation, but cannot find any not sure if I am missing anything or is this functionality not available in Unity-PowerShell?
Any help is greatly appreciated!

Please makes sure these boxes are checked before submitting your issue (put an X between the brackets).

- [X] Check that your Powershell version > 5.0 (Bonus point if you are using the latest version available)
- [X] Check that you follow the instructions for installing the module

Also, please provide:

- Any instructions that may help to reproduce the problem
- Informations about your host `$PSVerionTable`
- The list of the loaded modules `Get-Module`

**Comment by equelin** [comment]
Hello @arjun987,

This feature is note implemented yet in Unity-Powershell. At this time, I can't say when it will be available.

Regards

**Comment by agnosticcloud** [comment]
Thank you equelin.
I have another question, I am trying to understand the connect-unity.ps1 script which is used to connect to Unity. Can you please help me in understanding the script, and details like URI, headers, and the actual call itself. I am new to scripting and API, so any help will be greatly appreciated!
