### ISSUE TITLE
Consistency Group

### ISSUE THREAD

**Issue by dkoyadala** [equelin/Unity-Powershell#52]
Please makes sure these boxes are checked before submitting your issue (put an X between the brackets).

- [ ] Check that your Powershell version > 5.0 (Bonus point if you are using the latest version available)
- [ ] Check that you follow the instructions for installing the module

Also, please provide:

- Any instructions that may help to reproduce the problem
- Informations about your host `$PSVerionTable`
- The list of the loaded modules `Get-Module`

**Comment by equelin** [comment]
I need more information in order to help you on this one ;-)

Feel free to reopen the issue with more data
