### ISSUE TITLE
Set-UnityNFSShare - Request body is not correct error

### ISSUE THREAD

**Issue by atscomposer** [equelin/Unity-Powershell#53]
Seeing the following error with the set-unitynfsshare cmdlet:

The array sends an error message:

Error code: 422
Error description: Unprocessable Entity
Error details: {"error":{"errorCode":131149877,"httpStatusCode":422,"messages":[{"en-US":"Request body is not correct. There may be duplicate parameters, wrong parameter name
. Please refer to API documentation page and ensure the body is correct. (Error Code:0x7d13035)"}],"created":"2018-03-21T01:33:35.133Z"}}

Invoke-WebRequest : The remote server returned an error: (422) Unprocessable Entity.
At line:33 char:15
+ ...     $data = Invoke-WebRequest -Uri $URI -ContentType "application/jso ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Here is the verbose output as well as the command run:
PS C:\Windows\system32>                 Set-UnityNFSShare -Id $checkNewShare.id -rootAccessHosts $AccessHosts -append -confirm:$false -verbose

VERBOSE: GET https://10.72.5.150/api/types/system/instances with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; version=1.0;charset=UTF-8
VERBOSE: [Get-UnityObject] Object Type is String
VERBOSE: GET https://10.72.5.150/api/types/system/instances with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; version=1.0;charset=UTF-8
VERBOSE: GET https://10.72.5.150/api/types/nfsShare/instances?fields=filesystem,snap,description,type,readOnlyHosts,isReadOnly,nfsOwnerUsername,creationTime,readWriteHosts,ex
portPaths,name,noAccessHosts,id,modificationTime,path,rootAccessHosts,role,minSecurity,defaultAccess&compact=true with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; version=1.0;charset=UTF-8
VERBOSE: [Get-UnityObject] Object ID: NFSShare_106,Object Name: SRMDR-Colo_OVM
VERBOSE: GET https://10.72.5.150/api/types/system/instances with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; version=1.0;charset=UTF-8
VERBOSE: GET https://10.72.5.150/api/types/storageResource/instances?fields=sizeAllocated,luns,familyBaseStorageResource,compressionSizeSaved,hostVVolDatastore,type,snapSched
ule,blockHostAccess,metadataSizeAllocated,snapsSizeTotal,metadataSize,filesystem,esxFilesystemMajorVersion,isSnapSchedulePaused,vmwareUUID,parentSnap,snapsSizeAllocated,famil
ySnapCount,name,virtualVolumes,moves,datastores,esxFilesystemBlockSize,isReplicationDestination,replicationType,esxMountProtocol,thinStatus,pools,id,familyCloneCount,nonBaseS
izeAllocated,health,nonBaseSize,familySizeAllocatedTotal,sizeTotal,description,compressionPercent,compressionStatus,snapCount,sizeUsed,isThinClone,originalParentStorageResour
ce,compressionRatio,perTierSizeUsed&compact=true with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; version=1.0;charset=UTF-8
VERBOSE: {
    "nfsShareModify":  {
                           "nfsShareParameters":  {
                                                      "rootAccessHosts":  [
                                                                              {
                                                                                  "id":  "Host_7"
                                                                              },
                                                                              {
                                                                                  "id":  "Host_13"
                                                                              },
                                                                              {
                                                                                  "id":  "Host_15"
                                                                              },
                                                                              {
                                                                                  "id":  "Host_45"
                                                                              }
                                                                          ],
                                                      "isReadOnly":  false
                                                  },
                           "nfsShare":  {
                                            "id":  "NFSShare_106"
                                        }
                       }
}
VERBOSE: URL: https://10.72.5.150/api/instances/storageResource/res_18/action/modifyFilesystem
VERBOSE: Performing the operation "Modify NFS Share SRMDR-Colo_OVM" on target "Colo-Unity-01".
VERBOSE: POST https://10.72.5.150/api/instances/storageResource/res_18/action/modifyFilesystem with -1-byte payload

$PSVersionTable output:

Name                           Value                                                                                                                                         
----                           -----                                                                                                                                         
PSVersion                      5.1.14393.1770                                                                                                                                
PSEdition                      Desktop                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                       
BuildVersion                   10.0.14393.1770                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                               
WSManStackVersion              3.0                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                           
SerializationVersion           1.1.0.1  

Please makes sure these boxes are checked before submitting your issue (put an X between the brackets).

- [X] Check that your Powershell version > 5.0 (Bonus point if you are using the latest version available)
- [X] Check that you follow the instructions for installing the module

**Comment by equelin** [comment]
Hello @atscomposer,

Thanks for your feedback, you're right, the functions seems to have a bug maybe related to a new version of the API. I'm gonna take a look and provide a feedback later in the week.

**Comment by equelin** [comment]
Hello @atscomposer,

A fix to this issue is available in the develop branch (v0.16.1). I'll try to publish it on the Powershell gallery as soon as possible.

**Comment by equelin** [comment]
The fix is available in the Powershell gallery !

https://www.powershellgallery.com/packages/Unity-Powershell/0.16.1
