### ISSUE TITLE
D@RE key backup function

### ISSUE THREAD

**Issue by zerololcats** [equelin/Unity-Powershell#55]
Hi

I'm couldn't find a function to backup the D@RE key to a local directory. I'm hoping this can be added at some point. 

Thanks for making this thing it's crazy awesome!!!

**Comment by zerololcats** [comment]
Adding more information.

I tried using:

Get-UnityItem -URI '/download/encryption/keystore' -JSON > keys.lbb

and it did download something, but it doesn't look like the normal encrypted keys.

The file looks like this:

51
46
50
48
48
48
48
48
124
85
72...

While a normal .LBB file looks something like:

3.200000|UHJvZHVjdGlvbiBtb2RlIHNldCwgZmlsZSBjb250ZW50cyBlbmNyeXB0ZWQhCjUwLDM3CjQ0LDEzCnZjd...

Calling the API from my browser https://IP_ADDRESS/download/encryption/keystore does work and I get the file in the correct format.

Thanks!

**Comment by equelin** [comment]
Hello @zerololcats,

Thanks for your feedback and sorry if I didn't answer earlier... You're are right, those functions are not implemented now. To be honest, I don't know when I'll find time to do it... I'll keep you in touch if I can provide more information on that subject.

Concerning your question about Get-UnityItem, this function only performs a GET request so you will not be able to download anything with it.
