### ISSUE TITLE
Get-UnityDisk exceptions 

### ISSUE THREAD

**Issue by github-12341234** [equelin/Unity-Powershell#60]
Please makes sure these boxes are checked before submitting your issue (put an X between the brackets).

- [ X] Check that your Powershell version > 5.0 (Bonus point if you are using the latest version available)
- [ X] Check that you follow the instructions for installing the module

See "Get-UnityDatastore exceptions #59" for details about my installation.

When I run the "get-unitydisk" command I receive multiple exceptions (see below).

PS C:\> get-unitydisk
Exception setting "diskTechnology": "Cannot convert value "8" to type "DiskTechnologyEnum" due to enumeration values that are not valid. Specify one of the following enumeration
values and try again. The possible enumeration values are "SAS,NL_SAS,SAS_FLASH_2,SAS_FLASH_3,Mixed,Virtual"."
At line:29 char:46
+                 $Object."$($_.name)" = $D."$($_.name)"
+                                              ~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting

Id              Name             Rawsize       DiskTechnology Rpm Bankslot
--              ----             -------       -------------- --- --------
dae_0_1_disk_0  DAE 0 1 Drive 0  7523708960768 0              0

**Comment by github-12341234** [comment]
We are using "Flash 4" SSDs.
I do not see "FLASH_4" in your enum (per error message) so perhaps that is the issue.

**Comment by equelin** [comment]
Hello @github-12341234 , 

Thanks for your feedback, you're right all the enum related to the new version of the Unity OE are missing. Im curretly very busy at work so I don't know when I will be able to do that. Any help wouuld be very welcome !

**Comment by github-12341234** [comment]
I will ask management if I can devote time to this.  Likely they’ll so no.
