### ISSUE TITLE
Get-UnityESXi fails to product any useful output -- outputs error instead

### ISSUE THREAD

**Issue by github-12341234** [equelin/Unity-Powershell#61]
Please makes sure these boxes are checked before submitting your issue (put an X between the brackets).

- [ x] Check that your Powershell version > 5.0 (Bonus point if you are using the latest version available)
- [x ] Check that you follow the instructions for installing the module

See https://github.com/equelin/Unity-Powershell/issues/59 for details about my installation.

When I run the command "Get-UnityESXi" I receive only an error message, no useful info at all.:

> PS C:\> Get-UnityESXi
> Get-UnityItemByKey : Object(s) not found
> At line:53 char:7
> +       Get-UnityItemByKey -Session $Sess -URI $URI -Typename $Typename ...
> +       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-UnityItemByKey

**Comment by efd7887** [comment]
I am receiving the same message here.  
` 
Get-UnityVM -session $session
Get-UnityItemByKey : Object(s) not found
At line:52 char:7
+       Get-UnityItemByKey -Session $Sess -URI $URI -Typename $Typename ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-UnityItemByKey
 `

**Comment by efd7887** [comment]
Seems that a lot of the cmdlets throw this error

**Comment by equelin** [comment]
Hello,

Thanks for your feedback. Could you provide some informations about your setup ?

- Unity model
- Unity OE version
- Unity-Powershell module version

Regards,

**Comment by github-12341234** [comment]
Unity-650F

4.4.0.1534750794



$$PSVersionTable



Name                           Value

----                           -----

PSVersion                      6.1.0

PSEdition                      Core

GitCommitId                    6.1.0

OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Wed Oct 10 23:06:14 PDT 2018; root:xnu-4570.71.13~1/RELEASE_X86_64

Platform                       Unix

PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}

PSRemotingProtocolVersion      2.3

SerializationVersion           1.1.0.1

WSManStackVersion              3.0




Thanks!
