### ISSUE TITLE
connect-unity - strange issue

### ISSUE THREAD

**Issue by gman325** [equelin/Unity-Powershell#62]
Please makes sure these boxes are checked before submitting your issue (put an X between the brackets).

- [x] Check that your Powershell version > 5.0 (Bonus point if you are using the latest version available)
- [x] Check that you follow the instructions for installing the module

Also, please provide:

- Any instructions that may help to reproduce the problem
- Informations about your host `$PSVerionTable`
- The list of the loaded modules `Get-Module`

Hi 

PSVersion                      5.1.14393.2485
Unity-Powershell            0.16.1  

I am having a strange problem when using connect-unity. During my testing of the Unity-Powershell i logged into a windows server using my test account and I was able to connect to Unity without problems using a local Unity account. Now, if i log into the same server with another windows account and try to connect to Unity using same Unity local credentials as on initial logon with test account I get  below message. It seems that issue follows me no matter what server I connect from, I can only connect to unity successful while logged in as windows account I connected on the first time. It seems that something is cached on unity pointing to that windows account ( is there anything on the unity that can be cleared off )

WARNING: You are no longer connected to EMC Unity array: testarray
You are no longer connected to EMC Unity array: testarray
WARNING: You are no longer connected to EMC Unity array: testarray
WARNING: You are no longer connected to EMC Unity array: testarray

Any help would be appreciated.

**Comment by ChadSikorra** [comment]
Think I ran into this same thing. Might want to try the changes in https://github.com/equelin/Unity-Powershell/pull/72.

**Comment by d-works42** [comment]
I still have this issue when running connect-unity in the system context. Maybe the reason is that there is no "-UseBasicParsing" used in Send-UnityRequest.ps1?
