### ISSUE TITLE
Getting Duplicate outputs for all the the commands 

### ISSUE THREAD

**Issue by kakollu007** [equelin/Unity-Powershell#71]
Please makes sure these boxes are checked before submitting your issue (put an X between the brackets).

- [ X] Check that your Powershell version > 5.0 (Bonus point if you are using the latest version available)
- [ X] Check that you follow the instructions for installing the module

Also, please provide:

- Any instructions that may help to reproduce the problem
- Informations about your host `$PSVerionTable`
- The list of the loaded modules `Get-Module`

**Comment by equelin** [comment]
Hello @kakollu007,

You are maybe logged twice on your Unity. Just close your powershell session and retry the commands.
