### ISSUE TITLE
New-UnityCIFSShare missing snapshot parameter

### ISSUE THREAD

**Issue by d-works42** [equelin/Unity-Powershell#75]
I´m trying to create a CIFS share with New-UnityCIFSShare from a Snapshot with "filesystemAccessType Protocol". This works fine in the GUI but in New-UnityCIFSShare seem to be some parameter missing to set "type: Cifs_Snapshot".

**Comment by bradley-baker** [comment]
What's the status of this? We need to be able to create SMB shares against snapshots as well.
