### ISSUE TITLE
Cannot convert value to 6 when adding host to VMware LUN

### ISSUE THREAD

**Issue by TheGabeMan** [equelin/Unity-Powershell#76]
I have about 10 different Unity arrays in our environment, when masking a VMware LUN to a host is get below error messages for SOME arrays. I can't really figure out what makes the difference between the arrays that some don't and some do give the error.

Even though the error is thrown, the LUN is masked to the host, as requested.

Command:
**Set-UnityVMwareLUN -ID $LUN.id -host $HostFound.id -accessMask 'Production' -append -ErrorAction SilentlyContinue -WhatIf:$WhatIf -Confirm:$ConfirmAction**

Error:
```
Exception setting "esxFilesystemMajorVersion": "Cannot convert value "6" to type "ESXFilesystemMajorVersionEnum" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The po
ssible enumeration values are "VMFS_3,VMFS_5"."
At line:29 char:46
+                 $Object."$($_.name)" = $D."$($_.name)"
+                                              ~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting

```

- Informations about your host `$PSVerionTable`
PSVersion                      5.1.14409.1018

- The list of the loaded modules `Get-Module`
```
get-module | ft Name, version
Name                            Version
----                            -------
ISE                             1.0.0.0
Microsoft.PowerShell.Management 3.1.0.0
Microsoft.PowerShell.Security   3.0.0.0
Microsoft.PowerShell.Utility    3.1.0.0
Microsoft.WSMan.Management      3.0.0.0
Unity-Powershell                0.16.1 
```

**Comment by TheGabeMan** [comment]
There might be a pattern in the Unity firmware version. It seems this DOES happen on 5.x versions of Unity firmware (5.0.0.0.5.116), but not on 4.x (4.5.1.0.5.001).

**Comment by equelin** [comment]
Hello,

Thanks for your feedback. You're right, version 0.16.1 of the module is not compatible with OE 5.X...  Could you check with the latest version of the module 0.16.2 available in the Powershell Gallery?

**Comment by TheGabeMan** [comment]
I can confirm that with 16.2 I don't have these issues.
