### ISSUE TITLE
New-UnityLUN returns error when creating LUN in Unity 5.0.1

### ISSUE THREAD

**Issue by jzhang92** [equelin/Unity-Powershell#80]
Please makes sure these boxes are checked before submitting your issue (put an X between the brackets).

- [X ] Check that your Powershell version > 5.0 (Bonus point if you are using the latest version available)
- [X ] Check that you follow the instructions for installing the module

Also, please provide:

- Any instructions that may help to reproduce the problem

When running command to create new LUN in Unity 5.0.1:
New-UnityLUN -Name 'test1' -Pool 'pool_1' -Size 10GB

Returns with error:

The array sends an error message:

Error code: 422
Error description: Unprocessable Entity
Error details: {"error":{"errorCode":131149877,"httpStatusCode":422,"messages":[{"en-US":"Request body is not correct. There may be duplicate parameters, wrong parameter 
name. Please refer to API documentation page and ensure the body is correct. (Error Code:0x7d13035)"}],"created":"2020-01-13T05:54:05.400Z"}}

Invoke-WebRequest : The remote server returned an error: (422) Unprocessable Entity.
At line:33 char:15
+ ...     $data = Invoke-WebRequest -Uri $URI -ContentType "application/jso ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand 

- Informations about your host `$PSVerionTable`
$PSVersionTable

Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.17134.858                                                                                                                             
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.17134.858                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                                   

- The list of the loaded modules `Get-Module`
Get-Module

ModuleType Version    Name                                ExportedCommands                                                                                               
---------- -------    ----                                ----------------                                                                                               
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                            
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                             
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}                      
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                      
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}

**Comment by manisund** [comment]
isCompressionEnabled is deprecated in 5.0

Source : https://array_ip_or_fqdn/apidocs/classes/storageResource.html#bookmark_lunParameters 
On 4.5, it indicated already :
Deprecated: This attribute is obsolete and will be removed in a future release. Please use lunParameters.isDataReductionEnabled instead

Fix here is to remove that flag (4.5 will still work as that flag is optional) like:

<~/unity-ps> diff Unity-Powershell/Unity-Powershell/Public/New-UnityLUN.ps1 Unity-Powershell.orig/Unity-Powershell/Public/New-UnityLUN.ps1
24a25,26
>       .PARAMETER isCompressionEnabled
>       Indicates whether to enable inline compression for the LUN. Default is True on compatible arrays
70a73,74
>     [Parameter(Mandatory = $false,HelpMessage = 'Indicates whether to enable inline compression for the LUN. Default is True')]
>     [bool]$isCompressionEnabled,
121a126,131
>         }
>
>         If ($PSBoundParameters.ContainsKey('isCompressionEnabled')) {
>           $lunParameters["isCompressionEnabled"] = $isCompressionEnabled
>         } else {
>           $lunParameters["isCompressionEnabled"] = Test-CompressionUnsupported -Session $Sess -Pool $Pool

(Same to be done for Set-UnityLun.ps1 as well) 

I dont have right to push those changes here, Equelin need to update.

Example after fix:

PS C:\> Connect-Unity -server condor_array -Credentials $c

Server        User  Name          Model     SerialNumber
------        ----  ----          -----     ------------
condora admin 10.10.10.11 Unity 500 APM00123456

PS C:\> New-UnityLUN -Name 'PS_MANI_LUN100' -Pool 'pool_1' -Size '102
400' -Confirm:$false

Id    Name           Pool         IsThinEnabled TieringPolicy SizeTotal SizeAllocated Type
--    ----           ----         ------------- ------------- --------- ------------- ----
sv_26 PS_MANI_LUN100 @{id=pool_1} True          Autotier_High 102400    0             Standalone

**Comment by zayedm13** [comment]
Any update on this please?? not sure what is needed to report this. 

@equelin Please can you help us with this??

Please check Mani's update above.

Creating LUNs is no longer working after 5.0.
