### ISSUE TITLE
New-UnityVMWareLun unable to specify VMFS 5 or 6 - array defaults to v5

### ISSUE THREAD

**Issue by matt-matt2** [equelin/Unity-Powershell#91]
I am not sure why you would want a VMFS5 datastore! :)

**Comment by matt-matt2** [comment]
I'm trying to use the 0.16.2 module to automate some processes and not only does New-UnityVMwareLun fail for me on an array running 5.0.6 but I am not convinced I could use it anyway, as it seems to not offer the ability to select VMFS 6 datastore creation.
I will gather debug on the failure to create a separate incident if I can't figure out what I did wrong..

**Comment by WalshMichaelJames** [comment]
This was failing for me as well. I've edited the following in the file "Public/New-UnityVMwareLUN.ps1"

Remove lines 73& 74: 
    [Parameter(Mandatory = $false,HelpMessage = 'Indicates whether to enable inline compression for the LUN. Default is     True')]
    [bool]$isCompressionEnabled,


As well as 126-130
    If ($PSBoundParameters.ContainsKey('isCompressionEnabled')) {
        $lunParameters["isCompressionEnabled"] = $isCompressionEnabled
    } else {
        $lunParameters["isCompressionEnabled"] = Test-CompressionUnsupported -Session $Sess -Pool $Pool
    }



Then add in on the param section:
    # vmwareIscsiParameters
    [Parameter(Mandatory = $false,HelpMessage = 'Major Version of the VMFS? (Default is 6)')]
    [ESXFilesystemMajorVersionEnum]$majorVersion = '6'


And just before the "####### END BODY - Do not edit beyond this line"
    $vmwareIscsiParameters = @{}       
    $vmwareIscsiParameters["majorVersion"] = $majorVersion
    $body["vmwareIscsiParameters"] = $vmwareIscsiParameters



For my Unity version 5.1, I've had to change the following to allow for host mapping to work:
FROM:
    [HostLUNAccessEnum]$accessMask = 'Production',

TO
    [HostLUNAccessEnum]$accessMask = '1',
